module.exports = {
  produtos: [
    {
      id: 1,
      nome: 'Leite',
      descricao: 'Leite desnatado de 1 L',
      categoria: 'alimento',
      preco: 4,
    },
    {
      id: 2,
      nome: 'Monitor',
      descricao: 'Monitor widescreen de várias polegadas',
      categoria: 'informática',
      preco: 999,
    },
    {
      id: 3,
      nome: 'Desinfetante',
      descricao: 'Removedor de olho gordo para ambientes internos',
      categoria: 'casa',
      preco: 7,
    },
    {
      id: 4,
      nome: 'Sabonete',
      descricao: 'Sabonete líquido de 200 mL com aroma de rosas',
      categoria: 'higiene',
      preco: 2,
    },
    {
      id: 5,
      nome: 'Refrigerante',
      descricao: 'Bebida gaseificada de 2 L sabor guaraná',
      categoria: 'bebida',
      preco: 4,
    },
    {
      id: 6,
      nome: 'Fralda',
      descricao: 'Fralda invisível para quando estiver se borrando de medo',
      categoria: 'higiene',
      preco: 22,
    },
    {
      id: 7,
      nome: 'Mouse',
      descricao: 'Mouse gamer',
      categoria: 'informática',
      preco: 50,
    },
    {
      id: 8,
      nome: 'Cloro',
      descricao: 'Água sanitária de 2L',
      categoria: 'casa',
      preco: 3,
    },
  ],
}